name:  GitHub Actions Unit Tests

on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        cd services/api
        pipenv install --ignore-pipfile
    - name: Run tests with pytest
      env:
        REDDIT_USERNAME: ${{secrets.REDDIT_USERNAME}}
        REDDIT_PASSWORD: ${{secrets.REDDIT_PASSWORD}}
        REDDIT_CLIENT_ID: ${{secrets.REDDIT_CLIENT_ID}}
        REDDIT_CLIENT_SECRET: ${{secrets.REDDIT_CLIENT_SECRET}}
        REDDIT_USER_AGENT: ${{secrets.REDDIT_USER_AGENT}}
      run: |
        cd services/api
        pipenv run python -m pytest
